### ISSUE TITLE
flask_cdn.url_for raises AttributeError inside Blueprint with static_folder=None

### ISSUE THREAD

**Issue by jdp** [wichitacode/flask-cdn#8]
If you render a template that calls `flask_cdn.url_for` inside a Blueprint that does not have a `static_folder` set, it raises an `AttributeError`:

```
# traceback trimmed
File "/vagrant/templates/base.html", line 11, in top-level template code
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
  File "/home/vagrant/app-virtualenv/local/lib/python2.7/site-packages/flask_cdn.py", line 39, in url_for
    path = os.path.join(static_folder, values['filename'])
  File "/home/vagrant/app-virtualenv/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

It's because [`static_folder` defaults to `None` on `Blueprint` instances](http://flask.pocoo.org/docs/0.10/api/#blueprint-objects), it should probably use the app's static folder.

**Comment by jdp** [comment]
Looks like [this commit](https://github.com/snowtigersoft/flask-cdn/commit/4c023c988a2cd74b6c32609d00d2c657db360283) by @snowtigersoft fixes the issue, would be great to have upstream!

**Comment by loisaidasam** [comment]
:+1:

**Comment by libwilliam** [comment]
Thank you for the fix! Sorry I didn't get it in yesterday. I will try and put out a build today.

**Comment by libwilliam** [comment]
It is now on PyPI. Thank you again.
